name: 'Deploy to Codeberg Pages'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v4
      - run: |
            pnpm build
  deploy:
    runs-on: codeberg-tiny
    steps:
      - uses: https://codeberg.org/git-pages/action@v2
        with:
          site: 'https://bigheadcam.codeberg.page/cdmacdonald.com/'
          token: ${{ forge.token }}
          source: public/
